import type { Internship } from "./recommender";

// Expanded local dataset (INR) used as fallback and for offline/demo
// Logos use placeholder SVGs; replace with real company assets if available.
export const LOCAL_INTERNSHIPS: Internship[] = [
  {
    id: "tcs-dev-1",
    company: "Tata Consultancy Services",
    logo: "https://via.placeholder.com/60x60?text=TCS",
    title: "Software Development Intern",
    type: "paid",
    mode: "online",
    duration: "3 months",
    location: "Mumbai, Maharashtra",
    stipend: "₹15,000/month",
    skills: ["Java", "JavaScript", "Web Development", "Git"],
    description: "Work on web features with mentorship and code reviews.",
  },
  {
    id: "infosys-data-1",
    company: "Infosys",
    logo: "https://via.placeholder.com/60x60?text=INFO",
    title: "Data Analytics Intern",
    type: "paid",
    mode: "offline",
    duration: "6 months",
    location: "Bengaluru, Karnataka",
    stipend: "₹18,000/month",
    skills: ["Python", "SQL", "Data Analysis", "Excel"],
    description: "Analyze datasets and build dashboards for business insights.",
  },
  {
    id: "wipro-cloud-1",
    company: "Wipro",
    logo: "https://via.placeholder.com/60x60?text=WIPRO",
    title: "Cloud Computing Intern",
    type: "paid",
    mode: "online",
    duration: "4 months",
    location: "Hyderabad, Telangana",
    stipend: "₹16,000/month",
    skills: ["AWS", "DevOps", "Cloud Computing", "Linux"],
    description: "Deploy scalable solutions on AWS with CI/CD pipelines.",
  },
  {
    id: "hdfc-fa-1",
    company: "HDFC Bank",
    logo: "https://via.placeholder.com/60x60?text=HDFC",
    title: "Financial Analyst Intern",
    type: "paid",
    mode: "offline",
    duration: "3 months",
    location: "Mumbai, Maharashtra",
    stipend: "₹12,000/month",
    skills: ["Financial Analysis", "Excel", "Research"],
    description: "Support FP&A team with research and modelling.",
  },
  {
    id: "rel-mkt-1",
    company: "Reliance Industries",
    logo: "https://via.placeholder.com/60x60?text=REL",
    title: "Digital Marketing Intern",
    type: "unpaid",
    mode: "online",
    duration: "2 months",
    location: "New Delhi, Delhi",
    skills: ["Marketing", "Social Media", "Analytics"],
    description: "Plan and execute digital campaigns with content teams.",
  },
  {
    id: "itc-scm-1",
    company: "ITC Limited",
    logo: "https://via.placeholder.com/60x60?text=ITC",
    title: "Supply Chain Intern",
    type: "paid",
    mode: "offline",
    duration: "5 months",
    location: "Kolkata, West Bengal",
    stipend: "₹14,000/month",
    skills: ["Logistics", "Analytics", "Project Management"],
    description: "Optimize supply chain processes and reduce costs.",
  },
  {
    id: "tata-elx-ai-1",
    company: "Tata Elxsi",
    logo: "https://via.placeholder.com/60x60?text=TELX",
    title: "AI/ML Intern",
    type: "paid",
    mode: "online",
    duration: "3 months",
    location: "Pune, Maharashtra",
    stipend: "₹20,000/month",
    skills: ["Machine Learning", "Python", "Data Processing"],
    description: "Build starter ML models and evaluate performance.",
  },
  {
    id: "gov-agri-1",
    company: "AgriTech Startup (Gov Partner)",
    logo: "https://via.placeholder.com/60x60?text=AGRI",
    title: "Field Operations Intern",
    type: "paid",
    mode: "offline",
    duration: "3 months",
    location: "Bhopal, Madhya Pradesh",
    stipend: "₹8,000/month",
    skills: ["Field Work", "Communication", "Hindi"],
    description: "Assist farmer onboarding and data collection in districts.",
  },
  {
    id: "ngo-ed-1",
    company: "Education NGO",
    logo: "https://via.placeholder.com/60x60?text=NGO",
    title: "Education Program Intern",
    type: "unpaid",
    mode: "offline",
    duration: "2 months",
    location: "Lucknow, Uttar Pradesh",
    skills: ["Teaching", "MS Office", "Hindi"],
    description: "Support classroom activities for underprivileged students.",
  },
  {
    id: "startup-fe-1",
    company: "Gov SaaS Startup",
    logo: "https://via.placeholder.com/60x60?text=SaaS",
    title: "Frontend React Intern",
    type: "paid",
    mode: "online",
    duration: "3 months",
    location: "Remote, India",
    stipend: "₹12,000/month",
    skills: ["React", "TypeScript", "HTML", "CSS"],
    description: "Build accessible interfaces for government portals.",
  },
];


